server:
  port: 8123
  servlet:
    # 应用程序的上下文路径，也称为项目路径，是构成 URL 地址的一部分
    context-path: /api

spring:
  application:
    name: yu-picture-backend
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: 12345678lwx


mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志（sql语句）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除（列：isDelete ，删除：1 ，未删除：0 ）
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档（Swagger）
knife4j:
  enable: true
  openapi:
    title: 云图库接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.yupicturebackend.controller